# Site settings
title: "DevSecOps Podcast"
description: "O seu podcast sobre Segurança e Tecnologia"
podcast-description: "O DevSecOps Podcast é uma jornada empolgante pelo mundo da cibersegurança, com um foco especial em Application Security e DevSecOps. Neste podcast cativante, exploramos as mais recentes tendências, melhores práticas e desafios que cercam a proteção de aplicações e a integração da segurança não somente desde o início do ciclo de desenvolvimento de software., mas em toda sua execução Junte-se a especialistas do setor e líderes visionários enquanto discutem estratégias, ferramentas e insights essenciais para garantir que sua organização esteja à frente das ameaças cibernéticas. Se você está interessado em manter suas aplicações seguras e atualizado com as práticas mais recentes em segurança de desenvolvimento, o DevSecOps Podcast é o seu guia confiável."
url:  "https://cassiodeveloper.com.br/devsecopspodcast/" # Actual base url of the website
baseurl: "cassiodeveloper.com.br/devsecopspodcast/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Cássio Batista Pereira"
  email: "cassio@cassiobp.com.br"
  url: "https://cassiodeveloper.com.br"
permalink: pretty
permalink: /:title
keywords: [podcast, devsecops]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: cassiodeveloper
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Cássio Batista Pereira
  links:
    - https://github.com/cassiodeveloper
    - https://twitter.com/cassiodeveloper
    - https://www.linkedin.com/in/cassiodeveloper
lang: pt

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: DevSecOps Podcast
podcast_author: Cássio Batista Pereira
podcast_email: devsecopspodcast@gmail.com
podcast_subtitle: "O seu podcast sobre Segurança e Tecnologia"
podcast_summary: "DevSecOps de um jeito prático e descontraído."
podcast_description: "O DevSecOps Podcast é uma jornada empolgante pelo mundo da cibersegurança, com um foco especial em Application Security e DevSecOps. Neste podcast cativante, exploramos as mais recentes tendências, melhores práticas e desafios que cercam a proteção de aplicações e a integração da segurança não somente desde o início do ciclo de desenvolvimento de software., mas em toda sua execução Junte-se a especialistas do setor e líderes visionários enquanto discutem estratégias, ferramentas e insights essenciais para garantir que sua organização esteja à frente das ameaças cibernéticas. Se você está interessado em manter suas aplicações seguras e atualizado com as práticas mais recentes em segurança de desenvolvimento, o DevSecOps Podcast é o seu guia confiável."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: pt
podcast_launch: "2020-01-01" #Launch date of your podcast
podcast_copyright: "&#xA9;Cássio Batista Pereira"
podcast_feed: "https://www.spreaker.com/show/4179006/episodes/feed"
podcast_artwork: "/assets/img/Podcast_Cover.png"