analytics-id: G-37XY9E9BMP
#Pages
pages:
  - {name: 'Episódios', link: 'episodes.html'}

social:
  - {icon: 'instagram', type: "brand", link: 'https://www.instagram.com/cassiodeveloper'}
  - {icon: 'twitter', type: "brand", link: 'https://twitter.com/cassiodeveloper'}
  - {icon: 'facebook', type: "brand", link: 'https://facebook.com/cassiodeveloper'}
  - {icon: 'youtube', type: "brand", link: 'https://youtube.com/CassioBatistaPereira'}
  - {icon: 'envelope', type: "solid", link: 'mailto:cassio@cassiobp.com.br'}
  - {icon: 'rss', type: "solid", link: "https://www.spreaker.com/show/4179006/episodes/feed"}

websites-podcast:
  - {name: 'Apple Podcast', link: 'https://podcasts.apple.com/br/podcast/devsecops-podcast/id1493409525'}
  - {name: 'Spotify', link: 'https://open.spotify.com/show/25oDz3pL4HYy4wotJvVHDg?si=DvYstYoBSciyFxAn6pTDOg&nd=1https://open.spotify.com/show/25oDz3pL4HYy4wotJvVHDg?si=DvYstYoBSciyFxAn6pTDOg&nd=1'}
  - {name: 'YouTube', link: 'https://www.youtube.com/playlist?list=PLC2UsZBhySmJU0EYM6kzgchnXikYXZzmi'}
  - {name: 'Spreaker', link: 'https://www.spreaker.com/show/devsecops-podcast'}
  - {name: 'Google Podcast', link: 'https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuc3ByZWFrZXIuY29tL3Nob3cvNDE3OTAwNi9lcGlzb2Rlcy9mZWVk'}
  - {name: 'Castbox', link: 'https://castbox.fm/channel/id2535704'}
  - {name: 'RSS', link: 'https://www.spreaker.com/show/4179006/episodes/feed'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: false

#Disqus
disqus:
  disqus_shortname: cassiodeveloper